---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: pankaj
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pankaj
  template:
    metadata:
      labels:
        app: pankaj
    spec:
      containers:
      - name: hello-app
        image: gcr.io/seth-terraform/hellopnkj
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
spec:
  selector:
    app: pankaj
  type: LoadBalancer
  ports:
    - name: http
      protocol: 'TCP'
      port: 5000
      targetPort: 5000
